#!/bin/bash

. ./settings

BUILDDIR=`dirname "$0"`
BUILDFLAVOR="redhat"
#BUILDSUBFLAVOR="RH"

buildrpm() {

    # $1 = rpm/spec name
    # $2 = package name
    # $3 = build architecture
    # $4 = RH or SuSE
    # $5 = is site package?
    
    PKGNAME=$2
    BUILDARCH=$3
    BUILDSUBFLAVOR=$4
    
    # Pack all the additional files as extra sources
    [ "$BUILDSUBFLAVOR" != "" ] && FILESSUFFIX=".$BUILDSUBFLAVOR"
    pushd $BUILDDIR/files > /dev/null
    echo "Packaging all patches and additional files for: $PKGNAME"
    tar cvz --exclude=CVS $PKGNAME${FILESSUFFIX}/* > /usr/src/$BUILDFLAVOR/SOURCES/$PKGNAME.tar.gz 2>/dev/null
    cp -f /usr/src/$BUILDFLAVOR/SOURCES/$PKGNAME.tar.gz ./$PKGNAME$FILESSUFFIX.tar.gz # keep one for us
    popd > /dev/null

    # Copy the sources and patches
    cp -uf $BUILDDIR/src/* --target-directory=/usr/src/$BUILDFLAVOR/SOURCES
    cp -uf $BUILDDIR/patches/*.patch --target-directory=/usr/src/$BUILDFLAVOR/SOURCES

    # Build options 
    BUILDPLATFORM="$BUILDARCH-$BUILDFLAVOR-linux"

    SPEC="$BUILDDIR/$1.tpl.spec"
    SPECTMP="$BUILDDIR/$1.spec"

    # Patch the spec for TYPO version number and add subflavor-specific headers
    echo " " > $SPECTMP # to clear it
    cat $BUILDDIR/typo3-common.spec >> $SPECTMP
    echo " " >> $SPECTMP
    cat $SPEC >> $SPECTMP
    echo " " >> $SPECTMP
    if [ $5 ]; then
	cat $BUILDDIR/typo3-site-common.spec >> $SPECTMP
	echo " " >> $SPECTMP
    fi
    # Uncomment flavor-specific stuff
    sed -i "s/^#$BUILDSUBFLAVOR:\s*//" $SPECTMP
    grep -v "^#" $SPECTMP > $SPECTMP.r # remove comments
    mv -f $SPECTMP.r $SPECTMP

#    exit 0

    # Run the rpmbuild
    rpmbuild -ba --target=$BUILDPLATFORM $SPECTMP > /tmp/m1_build.out
    if [ "$?" == "0" ]; then
	rm /tmp/m1_build.out
	rm -f $BUILDDIR/rpmerror.out
    else
	echo "Error while building RPM. See details in rpmerror.out"
	mv /tmp/m1_build.out $BUILDDIR/rpmerror.out
	exit 1
    fi
    
    # Remove our temporary spec file
    rm $SPECTMP

    # move the file here
    mv /usr/src/$BUILDFLAVOR/RPMS/$BUILDARCH/$1*.rpm $BUILDDIR/rpm
    rm -f $BUILDDIR/rpm/*debug*.rpm
    
    # tell them everything is fine
    echo " "
    echo "Package '$2' built OK. Pick up the RPM at: $BUILDDIR/rpm/$1.rpm"
}

usage() {
    echo "Usage: $0 <package>"
    echo "Available package: ALL, typo3, ImageMagick4, quickstart, dummy, testsite."
    echo " "
}


if [ -z "$1" ]; then
    echo "TYPO3-BuildRPM"
    echo "Dimitri Tarassenko <m1tk4@hotmail.com>"
    echo " "
    usage
    exit 1
fi

case "$1" in 
    "ALL" )  
	;;
    "typo3" ) 
	buildrpm typo3 typo3 noarch RH
	buildrpm typo3 typo3 noarch SuSE
	;;
    "ImageMagick4" ) 
	buildrpm typo3-ImageMagick4 ImageMagick4 i386
	;;
    "quickstart" | "dummy" | "testsite" ) 
	buildrpm typo3-site-$1 $1 noarch RH 1
	buildrpm typo3-site-$1 $1 noarch SuSE 1
	;;
    * ) echo "ERROR: $1 is not a valid package"; usage; exit 1 ;;    
esac	

