#!/bin/bash

. ./settings

# Build options 
BUILDARCH="i386"
BUILDFLAVOR="redhat"
BUILDSUBFLAVOR="RH"
BUILDPLATFORM="$BUILDARCH-$BUILDFLAVOR-linux"
#BUILDDIR="/root/rpmtest" # DEBUG: should be the path of this script!
BUILDDIR=`dirname "$0"`
PLATFORMDIR="$BUILDDIR/platforms/$BUILDFLAVOR/$BUILDSUBFLAVOR"

SPEC="./typo3.tpl.spec"
SPECTMP="/typo3.spec"

# Pack all the additional files as extra sources
cd files
echo "Packaging all patches and additional files..."
for filedir in *
do
    if [ -d $filedir ] && [ "$filedir" != "CVS" ]; then
	echo "  - $filedir"
        tar cvz $filedir/* > /usr/src/$BUILDFLAVOR/SOURCES/$filedir.tar.gz 2>/dev/null
	cp /usr/src/$BUILDFLAVOR/SOURCES/$filedir.tar.gz ./$filedir.tar.gz # keep one for us
    fi
done
cd ..

#exit 1

# Copy all sources and patches
cp $BUILDDIR/src/* --target-directory=/usr/src/$BUILDFLAVOR/SOURCES
cp $BUILDDIR/patches/*.patch --target-directory=/usr/src/$BUILDFLAVOR/SOURCES

# Patch the spec for TYPO version number and add subflavor-specific headers
sed s/~~RPMRELEASE~~/$RPMRELEASE/ $PLATFORMDIR/headers.spec > $SPECTMP
echo >> $SPECTMP # make sure \n is at the end.
sed s/~~TYPOVERSION~~/$TYPOVERSION/g $SPEC >> $SPECTMP

# Run the rpm
rpmbuild -bb --target=$BUILDPLATFORM $SPECTMP > /tmp/m1_build.out
[ "$?" == "0" ] && rm /tmp/m1_build.out

# Remove our temporary spec file
rm $SPECTMP

# DEBUG get it here!
mv /usr/src/$BUILDFLAVOR/RPMS/i386/typo*.rpm $BUILDDIR/rpm


