#!/bin/sh

#
#  Set the default date and time format according to the system locale
#  preferred format.
#
#  Dimitri Tarassenko <m1tk4@hotmail.com>
#

# determine the date format
DATEFORMAT=`
    locale -ck LC_TIME | \
    grep ^d_fmt | \
    sed ' s/[%\"]//g; s/d_fmt\=//;' 
`
TIMEFORMAT=`
    locale -ck LC_TIME | \
    grep ^t_fmt\= | \
    sed ' s/[%\"]//g; s/t_fmt\=//; '
`
if [ "$TIMEFORMAT" == "R" ]; then
    TIMEFORMAT="H:i"
else
    TIMEFORMAT="h:ia"
fi

#"h:ia"
CURRENTLOCALE=`
    locale | \
    grep LC_TIME | \
    sed ' s/LC_TIME=//;'
`

if [ "$1" != "--force" ]; then

    echo "Run $0 --force to set the default TYPO3 date and time formats as follows:"
    echo " "
    echo "Date: $DATEFORMAT"
    echo "Time: $TIMEFORMAT"
    printf "\n(based on your current locale): $CURRENTLOCALE\n\n"
    
else

    # Now we really need to set it by patching the t3lib/config.default.php

    . `dirname $0`/common
    DEFAULTCONFIG="$TYPO3SRCPATH/t3lib/config_default.php"
    # change the date format
    awk '{ \
	if ( match ($0, /(.*ddmmyy.*=).*?(\/\/.*)$/, r)) \
	    print r[1] "> \"'$DATEFORMAT'\", " r[2];  \
	else \
	    print }' $DEFAULTCONFIG > $DEFAULTCONFIG.tmp
    # change the hour format
    awk '{ \
	if ( match ($0, /(.*hhmm.*=).*?(\/\/.*)$/, r)) \
	    print r[1] "> \"'$TIMEFORMAT'\", " r[2];  \
	else \
	    print }' $DEFAULTCONFIG.tmp > $DEFAULTCONFIG
    rm -f $DEFAULTCONFIG.tmp
    
fi
