#!/bin/bash

#
#	Clones a TYPO3-site
#

. `dirname $0`/common

usage() {
    echo "Usage: $0 <websitename> <clonename>"
    echo "TYPO3 Websites available for cloning:"
    pushd $TYPO3SITEPATH  >/dev/null
    for site in *; do
	if [ -d $site ] && [ -d /var/lib/mysql/t3$site ]; then
	    echo "  - $site"
	fi
    done
    popd >/dev/null
}

if [ -z $1 ] || [ -z $2 ]; then
    usage
    exit 1
fi

if [ -d $TYPO3SITEPATH/$1 ] && [ -d /var/lib/mysql/t3$1 ] ; then
    if [ -d $TYPO3SITEPATH/$2 ] || [ -d /var/lib/mysql/t3$2 ] ; then
	echo "ERROR: site '$2' already exists.";
	exit 1;
    fi
    echo "CLONING '$1' ==> '$2' ..."
    # copy the files
    mkdir -p $TYPO3SITEPATH/$2
    cp -rf $TYPO3SITEPATH/$1/* --target-directory=$TYPO3SITEPATH/$2
    cp -f /etc/httpd/conf.d/typo3-$1.conf /etc/httpd/conf.d/typo3-$2.conf
    sed -i s/$1/$2/g /etc/httpd/conf.d/typo3-$2.conf
    sed -i s/$1/$2/g /var/typo3/$2/typo3conf/localconf.php
    chown -R root.apache /var/typo3/$2
    chmod -R g+w,o-rwx  /var/typo3/$2
    # copy the database
    service mysqld status > /dev/null
    if [ "$?" != "0" ]; then
	service mysqld start
	sleep 2
    fi
    /usr/bin/mysql -e "create database t3$2;"
    /usr/bin/mysql -e "grant all privileges on t3$2.* to 't3$2'@'localhost' identified by 't3$2' WITH Grant option;"
    /usr/bin/mysqldump t3$1 | /usr/bin/mysql t3$2
    service httpd condrestart
    echo "Done."
    
else
    echo "ERROR: site '$1' not found."
    usage
    exit 1
fi